### ISSUE TITLE
dropdown menu에서 vertical menu style 질문이요

### ISSUE THREAD

**Issue by Huntak** [juijs/jui-grid#14]
vertical menu style도 아래처럼 dropdown 메뉴로 생성해서 show()와 hide()함수를 사용하는 것이 맞나요...?
vmenu를 addClass랑 removeClass 써서 구현하자면 구현할 수는 있겠지만 혹시나 만들어두신 function이 있으면 그걸 사용하려합니다....
감사합니다 ~~

```javascript
jui.ready([ "ui.dropdown" ], function(dropdown) {
	vmenu = dropdown("#vmenu", {
        event: {
            change: function(data) {
                alert(data.value + ", " + data.text);
            }
        }
    });
});
```

**Comment by easylogic** [comment]
사용하시는 방법이 맞습니다. 

기본적으로 show 로 화면 상에 보이는 위치로 옮길 수 있어서  show 메소드를 사용하기를 권장 드립니다. 

하지만  필요하시면 그냥 순수하게 class 를 바꾸셔도 무방합니다.

**Comment by Huntak** [comment]
tree를 사용하게 되었습니다....
아무튼 답변 감사드립니다 ^^
