### ISSUE TITLE
jui table을 window에서 생성 후 다시 열었을때 데이터를 찾지 못함

### ISSUE THREAD

**Issue by fullstop89** [juijs/jui-grid#17]
window에 table을 생성 후에 작업을 완료하고 다시 그 window를 열었을때

grid에 데이터가 나오지 않습니다.

데이터 자체는 찍히는데 실제 grid에 표현을 못해주는거 같아요

찾아보니 2015년에 저랑 거의 흡사한 내용이 있는데 해결이 완료 되지 않고 닫혔더라구요

table.destroy나 table = null을 하라고 답변해주셨는데 당시 질문자님도 해결이 안된다고 하셨구요

혹시 방법을 알려주실 수 있을까요

**Comment by seogi1004** [comment]
X-Table 객체는 여러개 생성하시면 안되고요.
하나만 생성해두시고, 윈도우가 보여질 때, resize 메소드를 호출해주시면 됩니다.
